version: "3.7"
services:
  php:
    container_name: skeleton-docker-php
    build: .
    #volumes:
      #- ../:/var/www/
    networks:
      - base
  nginx:
    container_name: skeleton-docker-nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - base
    env_file:
      - .env.nginx.local
networks:
  base:
