version: "3.7"
services:
  php:
    container_name: skeleton-docker-php
    build: .
    ports:
      - 8080:8080
    volumes:
      - ../:/var/www/
    networks:
      - base
  nginx:
    build:
      context: ./nginx
    ports:
      - 8001:80
    networks:
      - base
    env_file:
      - .env.nginx.local
networks:
  base:
