# This is a basic workflow to help you get started with Actions
# See https://docs.github.com/en/actions

name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for certain branches
  push:
    branches:
      - main
      - dev/*
      - ft/*
      - hotfix/*
      - tmp/*
      - v1.*
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull images
        run: docker-compose -f docker/docker-compose.yml pull --ignore-pull-failures || true

      - name: Start services
        run: docker-compose -f docker/docker-compose.yml up -d --build

      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose -f docker/docker-compose.yml ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy)
                docker-compose ps
                docker-compose logs
                exit 1
              ;;
            esac
          done
          exit 1

      - name: Check HTTP reachability
        run: curl -v -o /dev/null http://localhost:8080
